FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

# 安装依赖
RUN apt-get update && apt-get install -y \
    build-essential \
    git curl wget vim\
    cmake \
    ninja-build \
    pkg-config \
    gdb \
    zip unzip

# 复制脚本安装 miniconda
COPY install_miniconda.sh /tmp/install_miniconda.sh
RUN bash /tmp/install_miniconda.sh \
    && rm /tmp/install_miniconda.sh

# 安装 vcpkg（浅克隆，只拉最新快照，数据量远小于完整 clone）
RUN git clone --depth=1 https://github.com/microsoft/vcpkg.git /opt/vcpkg \
    && bash /opt/vcpkg/bootstrap-vcpkg.sh

# 配置环境变量
ENV PATH=\
/opt/miniconda/bin:\
/opt/vcpkg:\
${PATH}

# 安装 cmake_format
RUN pip install cmake_format


# 更新所有依赖
# RUN apt-get update && apt-get upgrade -y